# Generated by Django 4.1.3 on 2022-12-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Position',
            field=models.CharField(max_length=200),
        ),
    ]
